[ -f ~/.fehbg ] && sh ~/.fehbg &
dbus-daemon --print-address 4 --session
urxvtd -q -o -f
xautolock -detectsleep -time 5 -locker "i3lock -e -f -i /tmp/lockscreen.png" &
exec ssh-agent /home/jay/.local/bin/xmonad
