" Vim configuration 
" Based on https://github.com/dougblack/dotfiles/blob/master/.vimrc 

" Misc {{{
set backspace=indent,eol,start
set modeline
set modelines=1
set clipboard=unnamed
let mapleader = ","
" }}}

" Spaces & Tabs {{{
set tabstop=4           " 4 space tab
set expandtab           " use spaces for tabs
set softtabstop=4       " 4 space tab
set shiftwidth=4
" }}}

" UI Layout {{{
set number              " show line numbers
set showcmd             " show command in bottom bar
" set cursorline          " highlight current line
set wildmenu
set lazyredraw
set showmatch           " higlight matching parenthesis
" set fillchars+=vert:┃
" Show a line at 100 columns
set textwidth=100
set colorcolumn=+1

" Set up cursor line highlighting in insert mode.
augroup _cursor_mode
    autocmd!
    autocmd InsertEnter,InsertLeave * set cursorline!
augroup END

" }}}

" Searching {{{
set path+=**
set ignorecase          " ignore case when searching
set incsearch           " search as characters are entered
set hlsearch            " highlight all matches
" Set cursors for different modes
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"
" Turn off search highlights
nnoremap <leader><space> :nohlsearch<CR>
" }}}

" Folding {{{
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set foldenable          " don't fold files by default on open
nnoremap <space> za
set foldlevelstart=10   " start with fold level of 1
" }}}

" Line Shortcuts {{{
" nnoremap j gj
" nnoremap k gk
" nnoremap gV `[v`]
" }}}

" Backups {{{
set backup
set backupdir=~/.vim/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim/tmp,/var/tmp,/tmp
set writebackup
" }}}

" Plugins {{{
call plug#begin('~/.vim/plugged')
Plug 'altercation/vim-colors-solarized'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'preservim/nerdtree'
call plug#end()
" }}}

" Plugin configuration {{{

" Solarized toggle background
call togglebg#map("<F5>")

" Key bindings for fzf
nmap ; :Buffers<CR>
nmap <Leader>t :Tags<CR>
nmap <Leader>f :Files<CR>
nmap <Leader>a :Ag<CR>

" NerdTree key bindings
map <F2> :NERDTreeToggle<CR>

" }}}

" Filetype {{{
filetype indent on
filetype plugin on
set autoindent
" }}}

" Colors {{{
syntax enable           " enable syntax processing
colorscheme solarized
" set termguicolors
" }}}

" vim: foldmethod=marker:foldlevel=0
