#! /usr/bin/env bash
xrandr --dpi 96
xrdb -merge <<EOF 
Xft.dpi: 96
polybar.height: 24
polybar.tray-maxsize:16
EOF
i3-msg restart
sleep 1
nitrogen --restore
/usr/local/bin/make_lockscreen.sh &
sleep 1
MONITOR=DP1 polybar topbar &> /tmp/polybar-home.log &

