eval $(gnome-keyring-daemon --components=gpg,pkcs11,secrets,ssh --daemonize --login)
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_PID
nitrogen --restore &
dbus-daemon --print-address 4 --session
gnome-settings-daemon &
compton -f -b
urxvtd -q -o -f
pasystray &
blueman-applet &
nm-applet &
udiskie -q -t &
xautolock -detectsleep -time 5 -locker "i3lock -e -f -i /tmp/lockscreen.png" &
${HOME}/.local/bin/make_lockscreen.sh &
exec ssh-agent /usr/bin/i3
