[ -f ~/.fehbg ] && sh ~/.fehbg &
eval $(gnome-keyring-daemon --components=gpg,pkcs11,secrets,ssh --daemonize --login)
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_PID

dbus-daemon --print-address 4 --session
gnome-settings-daemon &
compton -f -b -i 0.9
urxvtd -q -o -f
# trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 3 --transparent true --alpha 64 --tint 0x000000 --height 19 &
# pasystray &
# blueman-applet &
# nm-applet &
xautolock -time 10 -locker /home/jay/.local/bin/fuzzylock.sh &
exec ssh-agent /usr/bin/awesome
