#! /usr/bin/env bash
xrandr --dpi 192
xrdb -merge <<EOF 
Xft.dpi: 192
polybar.height: 32
polybar.tray-maxsize:24
EOF
i3-msg restart
sleep 1
nitrogen --restore
/usr/local/bin/make_lockscreen.sh &
sleep 1
MONITOR=eDP1 polybar topbar &> /tmp/polybar-default.log
